### ISSUE TITLE
Malware Report

### ISSUE THREAD

**Issue by rskabc** [MATORINET/MIRAEASSET-MACOS#3]
- MacOS Version: [e.g. Big Sur]
 - Hots Version Release: [e.g. V.3.0]

Gen:Trojan.Heur.aO8@vmZwKr | Malware | rskabc | /Applications/HOTS 2.app/Contents/Resources/drive_c/windows/system32/stdole32.tlb
-- | -- | -- | --
Gen:Trojan.Heur.aO8@vmZwKr | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib32on64/wine/stdole32.tlb
Gen:Trojan.Heur.aO8@vmZwKr | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/Resources/drive_c/windows/system32/stdole32.tlb
Gen:Trojan.Heur.aO8@vmZwKr | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib32on64/wine/stdole32.tlb
Gen:Trojan.Heur.aO8@vmZwKr | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/Resources/drive_c/windows/system32/stdole32.tlb
Gen:Trojan.Heur.aO8@vmZwKr | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib32on64/wine/stdole32.tlb
Gen:Trojan.Heur.aO8@vmZwKr | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/Resources/drive_c/windows/system32/stdole32.tlb
Gen:Trojan.Heur.aO8@vmZwKr | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib32on64/wine/stdole32.tlb
Gen:Trojan.Heur.aO8@vuRmzoc | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib/wine/stdole32.tlb
Gen:Trojan.Heur.aO8@vuRmzoc | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib/wine/stdole32.tlb
Gen:Trojan.Heur.aO8@vuRmzoc | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib/wine/stdole32.tlb
Gen:Trojan.Heur.aO8@vuRmzoc | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib/wine/stdole32.tlb
Gen:Trojan.Heur.bO8@vaUqU2e | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib/wine/stdole2.tlb
Gen:Trojan.Heur.bO8@vaUqU2e | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib/wine/stdole2.tlb
Gen:Trojan.Heur.bO8@vaUqU2e | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib/wine/stdole2.tlb
Gen:Trojan.Heur.bO8@vaUqU2e | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib/wine/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | rskabc | /Applications/HOTS 2.app/Contents/Resources/drive_c/windows/system32/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib32on64/wine/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/Resources/drive_c/windows/system32/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib32on64/wine/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/Resources/drive_c/windows/system32/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib32on64/wine/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/Resources/drive_c/windows/system32/stdole2.tlb
Gen:Trojan.Heur.bO8@vef7Kef | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib32on64/wine/stdole2.tlb
Gen:Trojan.Heur.mS8@v07Uo8bi | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib/wine/inetcpl.cpl
Gen:Trojan.Heur.mS8@v07Uo8bi | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib/wine/inetcpl.cpl
Gen:Trojan.Heur.mS8@v07Uo8bi | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib/wine/inetcpl.cpl
Gen:Trojan.Heur.mS8@v07Uo8bi | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib/wine/inetcpl.cpl
Gen:Trojan.Heur.mS8@viiwgXgi | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib32on64/wine/inetcpl.cpl
Gen:Trojan.Heur.mS8@viiwgXgi | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib32on64/wine/inetcpl.cpl
Gen:Trojan.Heur.mS8@viiwgXgi | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib32on64/wine/inetcpl.cpl
Gen:Trojan.Heur.mS8@viiwgXgi | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib32on64/wine/inetcpl.cpl
Gen:Variant.Barys.80550 | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib/wine/wscript.exe
Gen:Variant.Barys.80550 | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib/wine/wscript.exe
Gen:Variant.Barys.80550 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib/wine/wscript.exe
Gen:Variant.Barys.80550 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib/wine/wscript.exe
Gen:Variant.Bulz.49290 | Malware | rskabc | /Applications/HOTS 2.app/Contents/Resources/drive_c/windows/system32/explorerframe.dll
Gen:Variant.Bulz.49290 | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib/wine/explorerframe.dll
Gen:Variant.Bulz.49290 | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/Resources/drive_c/windows/system32/explorerframe.dll
Gen:Variant.Bulz.49290 | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib/wine/explorerframe.dll
Gen:Variant.Bulz.49290 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/Resources/drive_c/windows/system32/explorerframe.dll
Gen:Variant.Bulz.49290 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib/wine/explorerframe.dll
Gen:Variant.Bulz.49290 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/Resources/drive_c/windows/system32/explorerframe.dll
Gen:Variant.Bulz.49290 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib/wine/explorerframe.dll
Gen:Variant.Fugrafa.114299 | Malware | rskabc | /Applications/HOTS 2.app/Contents/Resources/drive_c/windows/hh.exe
Gen:Variant.Fugrafa.114299 | Malware | rskabc | /Applications/HOTS 2.app/Contents/SharedSupport/wine/lib/wine/hh.exe
Gen:Variant.Fugrafa.114299 | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/Resources/drive_c/windows/hh.exe
Gen:Variant.Fugrafa.114299 | Malware | N/A | /System/Volumes/Data/Applications/HOTS.app/Contents/SharedSupport/wine/lib/wine/hh.exe
Gen:Variant.Fugrafa.114299 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/Resources/drive_c/windows/hh.exe
Gen:Variant.Fugrafa.114299 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app 21-43-20-608.app/Contents/SharedSupport/wine/lib/wine/hh.exe
Gen:Variant.Fugrafa.114299 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/Resources/drive_c/windows/hh.exe
Gen:Variant.Fugrafa.114299 | Malware | N/A | /System/Volumes/Data/Users/rskabc/.Trash/HOTS.app/Contents/SharedSupport/wine/lib/wine/hh.exe

**Comment by MATORINET** [comment]
Terimakasih atas laporannya bos , Kami tindak lanjuti segera

**Comment by MATORINET** [comment]
Terkait laporan malware memang kalau wine yang sudah ketambahan program di scan selalu muncul laporan malware , kami mendapati juga di program windows yang diinstall menggunakan crossover seperti winbox untuk remote perangkat MikroTik  dan masih banyak program lain yang ditemukan masalah terkait scanner malware .Beberapa file yang terindikasi sebuah malware sangat dibutuhkan oleh emulator agar berjalan lancar .
